sudo: false
language: go
go:
- 1.4
install:
- go get github.com/spf13/hugo
script: hugo
deploy:
  provider: gcs
  access_key_id: GOOGSFHYUUIZXS2HYPUB
  secret_access_key:
    secure: GJDAdjIs8hdWkuc56hk8Tvfxem+9l25Yc1kf9V+kjad2xoy40wsVXNljyaORXYwVfdXJT9STBYCRSMGyUdMDa57Qo5Iir7Rcaaq/q6zynfziVKxZ0tb5jUQWyNrPsqzpL+Cvk3dEKTBwwo6g0X4TXLpwpDNg872HUE3ftrS/6MI=
  bucket: mindflakes.com
  local-dir: public
  on:
    repo: nelsonjchen/mindflakes.com
    branch: master
