sudo: false
install:
  - wget -O hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v0.52/hugo_0.52_Linux-64bit.tar.gz"
  - mkdir bin
  - tar xf ./hugo.tar.gz --exclude "*.md" -C bin
  - export PATH="${TRAVIS_BUILD_DIR}/bin:$PATH"
script: hugo
deploy:
  provider: gcs
  access_key_id: GOOGSFHYUUIZXS2HYPUB
  secret_access_key:
    secure: GJDAdjIs8hdWkuc56hk8Tvfxem+9l25Yc1kf9V+kjad2xoy40wsVXNljyaORXYwVfdXJT9STBYCRSMGyUdMDa57Qo5Iir7Rcaaq/q6zynfziVKxZ0tb5jUQWyNrPsqzpL+Cvk3dEKTBwwo6g0X4TXLpwpDNg872HUE3ftrS/6MI=
  bucket: mindflakes.com
  local-dir: public
  skip_cleanup: true
  acl: public_read
  on:
    repo: nelsonjchen/mindflakes.com
    branch: master
